Integração do extrator de arquivos binários
MPMG-DCC-UFMG/C04 pull request #209
Opened 2020-09-09 00:43 UTC by louisaturn

- Alterações no base_spider e no processo de armazenamento do extrator;
- Chamada do servidor tika para o extrator binário;
- Adaptações nos testes de unidade, bem como adição dos arquivos faltantes para o funcionamento dos testes.
   (Importante frisar que utilizei um add -f para disponibilizar arquivo em formato pdf).

2020-09-09 00:43 UTC, pep8speaks commented
Hello @louisaturn! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`crawlers/base_spider.py`](https://github.com/MPMG-DCC-UFMG/C04/blob/536e8cdef03db8c3a03d2cb9c4d2e9281daafd03/crawlers/base_spider.py):

> [Line 30:1](https://github.com/MPMG-DCC-UFMG/C04/blob/536e8cdef03db8c3a03d2cb9c4d2e9281daafd03/crawlers/base_spider.py#L30): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace



* In the file [`src/binary_extractor/binary/__main__.py`](https://github.com/MPMG-DCC-UFMG/C04/blob/536e8cdef03db8c3a03d2cb9c4d2e9281daafd03/src/binary_extractor/binary/__main__.py):

> [Line 11:1](https://github.com/MPMG-DCC-UFMG/C04/blob/536e8cdef03db8c3a03d2cb9c4d2e9281daafd03/src/binary_extractor/binary/__main__.py#L11): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 27:5](https://github.com/MPMG-DCC-UFMG/C04/blob/536e8cdef03db8c3a03d2cb9c4d2e9281daafd03/src/binary_extractor/binary/__main__.py#L27): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '

* In the file [`src/binary_extractor/binary/binary_extractor.py`](https://github.com/MPMG-DCC-UFMG/C04/blob/536e8cdef03db8c3a03d2cb9c4d2e9281daafd03/src/binary_extractor/binary/binary_extractor.py):

> [Line 45:57](https://github.com/MPMG-DCC-UFMG/C04/blob/536e8cdef03db8c3a03d2cb9c4d2e9281daafd03/src/binary_extractor/binary/binary_extractor.py#L45): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator



* In the file [`src/binary_extractor/tests/unit_test.py`](https://github.com/MPMG-DCC-UFMG/C04/blob/536e8cdef03db8c3a03d2cb9c4d2e9281daafd03/src/binary_extractor/tests/unit_test.py):

> [Line 25:8](https://github.com/MPMG-DCC-UFMG/C04/blob/536e8cdef03db8c3a03d2cb9c4d2e9281daafd03/src/binary_extractor/tests/unit_test.py#L25): [E222](https://duckduckgo.com/?q=pep8%20E222) multiple spaces after operator
> [Line 95:80](https://github.com/MPMG-DCC-UFMG/C04/blob/536e8cdef03db8c3a03d2cb9c4d2e9281daafd03/src/binary_extractor/tests/unit_test.py#L95): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (83 > 79 characters)

2020-09-09 00:45 UTC, louisaturn commented
@pep8speaks pep8ify

2020-09-09 00:45 UTC, pep8speaks commented
Here you go with [the Pull Request](https://github.com/MPMG-DCC-UFMG/C04/pull/210) ! The fixes are suggested by [autopep8](https://github.com/hhatto/autopep8).

 @louisaturn

2020-09-09 23:54 UTC, lucasaug reviewed
O código está ótimo, e gostei da refatoração dos testes. Só encontrei alguns pequenos detalhes:

- O binary_extractor tem mensagens de erro em português, mas como a interface está em inglês acho que faria sentido que as mensagens de erro também estivessem (talvez vale debater isso com a equipe toda)
- Talvez poderia também mudar o nome do arquivo `unit_test.py` pra algo começado com `test_`, pra seguir o padrão dos outros módulos.

Mas são realmente detalhes bem pequenos, e o código ficou bem claro e legível. Testando localmente os testes passaram e a integração funcionou.

2020-09-09 23:54 UTC, lucasaug commented on src/binary_extractor/binary/__main__.py
>      main()
Coisa bem simples, mas acima você mudou a main pra receber o nome do arquivo, mas aqui em baixo não. Não sei se você quis passar aqui o valor em `sys.argv[1]`

2020-09-09 23:54 UTC, lucasaug commented on src/binary_extractor/setup.py
> +    install_requires=['tika', 'tabula-py', 'pandas', 'pathlib']
Eu adicionaria aqui também as bibliotecas `filetype` e `xlrd`, que precisei instalar na hora de rodar.

2020-09-09 23:54 UTC, lucasaug commented on src/binary_extractor/tests/unit_test.py
> +        path = str(Path.cwd().joinpath('tests/test_files/files/Edital.pdf'))
Aqui acho que você poderia ter usado a variável `edital`

2020-09-09 23:54 UTC, lucasaug commented on src/binary_extractor/binary/__main__.py
> +    #filepath = sys.argv[1]
Caso não tenha sido intencional, acho que vale remover esse comentário

2020-09-10 00:06 UTC, louisaturn commented on src/binary_extractor/binary/__main__.py
>      main()
Esse arquivo ficou inutilizado pela integração, mas quando eu achei que ia usar acabei alterando (haha). Desatenção mesmo! Vou desfazer a mudança.

2020-09-10 01:03 UTC, louisaturn commented
@pep8speaks suggest diff

2020-09-10 01:03 UTC, pep8speaks commented
Here you go with [the gist](https://gist.github.com/e43bb0eb146e3e454eb6c9ad1ddbfceb) !

> You can ask me to create a PR against this branch with those fixes. Simply comment `@pep8speaks pep8ify`.

 @louisaturn

2020-09-10 01:04 UTC, louisaturn commented
@pep8speaks pep8ify

2020-09-10 01:05 UTC, pep8speaks commented
Here you go with [the Pull Request](https://github.com/MPMG-DCC-UFMG/C04/pull/213) ! The fixes are suggested by [autopep8](https://github.com/hhatto/autopep8).

 @louisaturn

2020-09-10 01:25 UTC, lucasaug approved these changes

2020-09-10 13:53 UTC, gabrielcrds commented on src/binary_extractor/tests/test_binary.py
> +cotacao = str(Path.cwd().joinpath('tests/test_files/files/Cotacao.xlsx'))
Pelo que entendi essas variáveis só são acessadas pela classe né? Se for o caso, por que não transforma elas em variáveis estáticas da classe?

2020-09-10 14:03 UTC, gabrielcrds requested changes
Os arquivos de teste devem ficar na pasta _tests_ na raíz do repositório, não dentro do módulo em _src_, pois ai o workflow de testes vai conseguir encontrá-los.

2020-09-10 23:15 UTC, louisaturn commented
@pep8speaks suggest diff

2020-09-10 23:21 UTC, lucasaug approved these changes

2020-09-11 14:07 UTC, gabrielcrds approved these changes

2020-09-11 15:52 UTC, merged