Issue 314: Instances.json
MPMG-DCC-UFMG/C04 pull request #341
Opened 2020-11-27 00:06 UTC by elvesrodrigues

Adiciona a pasta `instances` as da coletas, contendo o arquivo `instances_info.json` registrando quando uma instância foi criada, iniciada e finalizada.

2020-11-27 00:06 UTC, pep8speaks commented
Hello @elvesrodrigues! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`crawlers/crawler_manager.py`](https://github.com/MPMG-DCC-UFMG/C04/blob/7c05776199c04cbbe0af16a194f84d10f7bbd427/crawlers/crawler_manager.py):

> [Line 148:1](https://github.com/MPMG-DCC-UFMG/C04/blob/7c05776199c04cbbe0af16a194f84d10f7bbd427/crawlers/crawler_manager.py#L148): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 189:80](https://github.com/MPMG-DCC-UFMG/C04/blob/7c05776199c04cbbe0af16a194f84d10f7bbd427/crawlers/crawler_manager.py#L189): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (81 > 79 characters)
> [Line 190:80](https://github.com/MPMG-DCC-UFMG/C04/blob/7c05776199c04cbbe0af16a194f84d10f7bbd427/crawlers/crawler_manager.py#L190): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (109 > 79 characters)
> [Line 191:1](https://github.com/MPMG-DCC-UFMG/C04/blob/7c05776199c04cbbe0af16a194f84d10f7bbd427/crawlers/crawler_manager.py#L191): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 197:50](https://github.com/MPMG-DCC-UFMG/C04/blob/7c05776199c04cbbe0af16a194f84d10f7bbd427/crawlers/crawler_manager.py#L197): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace

* In the file [`crawlers/static_page.py`](https://github.com/MPMG-DCC-UFMG/C04/blob/7c05776199c04cbbe0af16a194f84d10f7bbd427/crawlers/static_page.py):

> [Line 150:80](https://github.com/MPMG-DCC-UFMG/C04/blob/7c05776199c04cbbe0af16a194f84d10f7bbd427/crawlers/static_page.py#L150): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (89 > 79 characters)

2020-11-27 00:09 UTC, elvesrodrigues commented
@pep8speaks pep8ify

2020-11-27 00:09 UTC, pep8speaks commented
Here you go with [the Pull Request](https://github.com/MPMG-DCC-UFMG/C04/pull/342) ! The fixes are suggested by [autopep8](https://github.com/hhatto/autopep8).

 @elvesrodrigues

2020-12-01 12:16 UTC, gabrielcrds commented on crawlers/static_page.py
> -        if config[attr] is not None and type(config[attr]) is str:
Tem um outro PR arrumando isso especificamente isso, que inclusive modifica só essa linha. Pode desfazer essa alteração e aprovar o outro pr? [link](https://github.com/MPMG-DCC-UFMG/C04/pull/346)

2020-12-01 12:22 UTC, gabrielcrds requested changes

2020-12-01 12:22 UTC, gabrielcrds commented on main/models.py
> +    finished_at = models.DateTimeField(null=True, blank=True)
Esse modelo herda de TimeStamped, que já possui atributos com essa funcionalidade que são atualizados automaticamente (creation_date e last_modified). Não da pra usar esses atributos pra pegar as informações que precisa?

2020-12-01 12:22 UTC, gabrielcrds commented on crawlers/crawler_manager.py
> +    filename = f"{data_path}/instances/instances_info.json"
Se a pasta vai conter só esse arquivo, não acha que faz sentido deixar só o arquivo na pasta raiz do coletor? Por ex, ``coleta/contagem/instances_info.json`` ao invés de ``coleta/contagem/instances/instances_info.json``

2020-12-01 12:33 UTC, elvesrodrigues commented on main/models.py
> +    finished_at = models.DateTimeField(null=True, blank=True)
Sim, inclusive era o que eu iria fazer. Porém achei que, para quem nunca viu o código, estas variáveis/campos acima seriam mais descritivos.

Mas posso alterar para utilizar eles.

2020-12-01 12:36 UTC, elvesrodrigues commented on crawlers/crawler_manager.py
> +    filename = f"{data_path}/instances/instances_info.json"
Sim, faz sentido.

2020-12-02 20:08 UTC, gabrielcrds approved these changes

2020-12-02 21:32 UTC, LorenaMendes approved these changes

2020-12-03 20:01 UTC, merged