Issue 296 - Adiciona os mecanismos de antiblock do Requests
MPMG-DCC-UFMG/C04 pull request #359
Opened 2020-12-04 06:52 UTC by lucasaug

Cria uma interface para utilização dos mecanismos de antiblock já presentes no Scrapy na biblioteca Requests.

2020-12-04 06:53 UTC, pep8speaks commented
Hello @lucasaug! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:



* In the file [`src/antiblock_drivers/antiblock_drivers/antiblock_general.py`](https://github.com/MPMG-DCC-UFMG/C04/blob/eab869252a0aaedeb9aa28307cb7dec46b27a394/src/antiblock_drivers/antiblock_drivers/antiblock_general.py):

> [Line 14:1](https://github.com/MPMG-DCC-UFMG/C04/blob/eab869252a0aaedeb9aa28307cb7dec46b27a394/src/antiblock_drivers/antiblock_drivers/antiblock_general.py#L14): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 31:17](https://github.com/MPMG-DCC-UFMG/C04/blob/eab869252a0aaedeb9aa28307cb7dec46b27a394/src/antiblock_drivers/antiblock_drivers/antiblock_general.py#L31): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 37:17](https://github.com/MPMG-DCC-UFMG/C04/blob/eab869252a0aaedeb9aa28307cb7dec46b27a394/src/antiblock_drivers/antiblock_drivers/antiblock_general.py#L37): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 43:17](https://github.com/MPMG-DCC-UFMG/C04/blob/eab869252a0aaedeb9aa28307cb7dec46b27a394/src/antiblock_drivers/antiblock_drivers/antiblock_general.py#L43): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 48:17](https://github.com/MPMG-DCC-UFMG/C04/blob/eab869252a0aaedeb9aa28307cb7dec46b27a394/src/antiblock_drivers/antiblock_drivers/antiblock_general.py#L48): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 66:13](https://github.com/MPMG-DCC-UFMG/C04/blob/eab869252a0aaedeb9aa28307cb7dec46b27a394/src/antiblock_drivers/antiblock_drivers/antiblock_general.py#L66): [E125](https://duckduckgo.com/?q=pep8%20E125) continuation line with same indent as next logical line
> [Line 70:13](https://github.com/MPMG-DCC-UFMG/C04/blob/eab869252a0aaedeb9aa28307cb7dec46b27a394/src/antiblock_drivers/antiblock_drivers/antiblock_general.py#L70): [E125](https://duckduckgo.com/?q=pep8%20E125) continuation line with same indent as next logical line
> [Line 81:13](https://github.com/MPMG-DCC-UFMG/C04/blob/eab869252a0aaedeb9aa28307cb7dec46b27a394/src/antiblock_drivers/antiblock_drivers/antiblock_general.py#L81): [E125](https://duckduckgo.com/?q=pep8%20E125) continuation line with same indent as next logical line
> [Line 153:50](https://github.com/MPMG-DCC-UFMG/C04/blob/eab869252a0aaedeb9aa28307cb7dec46b27a394/src/antiblock_drivers/antiblock_drivers/antiblock_general.py#L153): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 255:12](https://github.com/MPMG-DCC-UFMG/C04/blob/eab869252a0aaedeb9aa28307cb7dec46b27a394/src/antiblock_drivers/antiblock_drivers/antiblock_general.py#L255): [E114](https://duckduckgo.com/?q=pep8%20E114) indentation is not a multiple of four (comment)
> [Line 256:12](https://github.com/MPMG-DCC-UFMG/C04/blob/eab869252a0aaedeb9aa28307cb7dec46b27a394/src/antiblock_drivers/antiblock_drivers/antiblock_general.py#L256): [E111](https://duckduckgo.com/?q=pep8%20E111) indentation is not a multiple of four
> [Line 257:12](https://github.com/MPMG-DCC-UFMG/C04/blob/eab869252a0aaedeb9aa28307cb7dec46b27a394/src/antiblock_drivers/antiblock_drivers/antiblock_general.py#L257): [E111](https://duckduckgo.com/?q=pep8%20E111) indentation is not a multiple of four
> [Line 308:27](https://github.com/MPMG-DCC-UFMG/C04/blob/eab869252a0aaedeb9aa28307cb7dec46b27a394/src/antiblock_drivers/antiblock_drivers/antiblock_general.py#L308): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ':'
> [Line 309:28](https://github.com/MPMG-DCC-UFMG/C04/blob/eab869252a0aaedeb9aa28307cb7dec46b27a394/src/antiblock_drivers/antiblock_drivers/antiblock_general.py#L309): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ':'
> [Line 330:22](https://github.com/MPMG-DCC-UFMG/C04/blob/eab869252a0aaedeb9aa28307cb7dec46b27a394/src/antiblock_drivers/antiblock_drivers/antiblock_general.py#L330): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 331:22](https://github.com/MPMG-DCC-UFMG/C04/blob/eab869252a0aaedeb9aa28307cb7dec46b27a394/src/antiblock_drivers/antiblock_drivers/antiblock_general.py#L331): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 361:13](https://github.com/MPMG-DCC-UFMG/C04/blob/eab869252a0aaedeb9aa28307cb7dec46b27a394/src/antiblock_drivers/antiblock_drivers/antiblock_general.py#L361): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 365:36](https://github.com/MPMG-DCC-UFMG/C04/blob/eab869252a0aaedeb9aa28307cb7dec46b27a394/src/antiblock_drivers/antiblock_drivers/antiblock_general.py#L365): [E127](https://duckduckgo.com/?q=pep8%20E127) continuation line over-indented for visual indent

* In the file [`src/antiblock_drivers/antiblock_drivers/antiblock_requests.py`](https://github.com/MPMG-DCC-UFMG/C04/blob/eab869252a0aaedeb9aa28307cb7dec46b27a394/src/antiblock_drivers/antiblock_drivers/antiblock_requests.py):

> [Line 9:1](https://github.com/MPMG-DCC-UFMG/C04/blob/eab869252a0aaedeb9aa28307cb7dec46b27a394/src/antiblock_drivers/antiblock_drivers/antiblock_requests.py#L9): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 56:67](https://github.com/MPMG-DCC-UFMG/C04/blob/eab869252a0aaedeb9aa28307cb7dec46b27a394/src/antiblock_drivers/antiblock_drivers/antiblock_requests.py#L56): [W292](https://duckduckgo.com/?q=pep8%20W292) no newline at end of file





* In the file [`src/entry_probing/entry_probing/entry_probing_request.py`](https://github.com/MPMG-DCC-UFMG/C04/blob/eab869252a0aaedeb9aa28307cb7dec46b27a394/src/entry_probing/entry_probing/entry_probing_request.py):

> [Line 72:5](https://github.com/MPMG-DCC-UFMG/C04/blob/eab869252a0aaedeb9aa28307cb7dec46b27a394/src/entry_probing/entry_probing/entry_probing_request.py#L72): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)

* In the file [`tests/test_antiblock_drivers/test_antiblock_driver.py`](https://github.com/MPMG-DCC-UFMG/C04/blob/eab869252a0aaedeb9aa28307cb7dec46b27a394/tests/test_antiblock_drivers/test_antiblock_driver.py):

> [Line 8:1](https://github.com/MPMG-DCC-UFMG/C04/blob/eab869252a0aaedeb9aa28307cb7dec46b27a394/tests/test_antiblock_drivers/test_antiblock_driver.py#L8): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 64:38](https://github.com/MPMG-DCC-UFMG/C04/blob/eab869252a0aaedeb9aa28307cb7dec46b27a394/tests/test_antiblock_drivers/test_antiblock_driver.py#L64): [E201](https://duckduckgo.com/?q=pep8%20E201) whitespace after '{'
> [Line 64:48](https://github.com/MPMG-DCC-UFMG/C04/blob/eab869252a0aaedeb9aa28307cb7dec46b27a394/tests/test_antiblock_drivers/test_antiblock_driver.py#L64): [E202](https://duckduckgo.com/?q=pep8%20E202) whitespace before '}'
> [Line 70:25](https://github.com/MPMG-DCC-UFMG/C04/blob/eab869252a0aaedeb9aa28307cb7dec46b27a394/tests/test_antiblock_drivers/test_antiblock_driver.py#L70): [E201](https://duckduckgo.com/?q=pep8%20E201) whitespace after '{'
> [Line 70:35](https://github.com/MPMG-DCC-UFMG/C04/blob/eab869252a0aaedeb9aa28307cb7dec46b27a394/tests/test_antiblock_drivers/test_antiblock_driver.py#L70): [E202](https://duckduckgo.com/?q=pep8%20E202) whitespace before '}'
> [Line 74:5](https://github.com/MPMG-DCC-UFMG/C04/blob/eab869252a0aaedeb9aa28307cb7dec46b27a394/tests/test_antiblock_drivers/test_antiblock_driver.py#L74): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)
> [Line 80:29](https://github.com/MPMG-DCC-UFMG/C04/blob/eab869252a0aaedeb9aa28307cb7dec46b27a394/tests/test_antiblock_drivers/test_antiblock_driver.py#L80): [E203](https://duckduckgo.com/?q=pep8%20E203) whitespace before ':'
> [Line 87:29](htt [...]

2020-12-04 06:53 UTC, lucasaug commented
@pep8speaks pep8ify

2020-12-04 06:54 UTC, pep8speaks commented
Here you go with [the Pull Request](https://github.com/MPMG-DCC-UFMG/C04/pull/360) ! The fixes are suggested by [autopep8](https://github.com/hhatto/autopep8).

 @lucasaug

2020-12-09 14:46 UTC, elvesrodrigues requested changes

2020-12-09 14:46 UTC, elvesrodrigues commented on src/antiblock_drivers/antiblock_drivers/antiblock_general.py
> +            self.__validate_ip_config()
Aparentemente, este método não foi definido.

2020-12-10 12:32 UTC, elvesrodrigues approved these changes

2020-12-10 18:47 UTC, gabrielcrds approved these changes

2020-12-10 19:07 UTC, merged